name: Docker Build and Push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: 
  #schedule:
    #- cron: '0 0 * * *' # Runs at 00:00 UTC daily
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

permissions: # The permissions that the workflow has. The permissions are inherited from the job and can be customized.
  contents: write

env: 
  GRASS_IMAGE_NAME: 'qnistar/grass'
  GRASS_NODE_IMAGE_NAME: 'qnistar/grass-node'
  GRASS_DESKTOP_IMAGE_NAME: 'qnistar/grass-desktop'
  #TAG: 'latest'
  #TAG: '5.1.0'
  #TAG: '4.32.0'
  TAG: '5.1.1'
  
  MAX_DELAY: 30
  GRASS_VERSION_FILE_PATH: '.githubworkflows.grass_current_version'
  GRASS_NODE_VERSION_FILE_PATH: '.githubworkflows.grass-node_current_version'
  GRASS_DESKTOP_VERSION_FILE_PATH: '.githubworkflows.grass-desktop_current_version'
  GRASS_RELEASE_URL: 'https://chromewebstore.google.com/detail/${{ secrets.EXTENSION_ID }}'
  GRASS_NODE_RELEASE_URL: 'https://api.getgrass.io/extensionLatestRelease'
  GRASS_DESKTOP_RELEASE_URL: 'https://api.getgrass.io/desktopLatestRelease' # Placeholder URL

jobs: 
  build-and-push: 
    runs-on: ubuntu-latest
    steps: 
      - name: Randomized Delay
        run: sleep $((RANDOM % ${{ env.MAX_DELAY }}))

      - name: Install jq tool # Useful for parsing JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine if Forced Build
        id: force-check
        run: |
          FORCE_BUILD="false"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            FORCE_BUILD="true"
          fi
          echo "force_build=$FORCE_BUILD" >> $GITHUB_ENV

      


      - name: Setup QEMU
        #if: steps.grass-version-check.outputs.grass_build == 'true' || steps.grass-node-version-check.outputs.grass_node_build == 'true' || steps.grass-desktop-version-check.outputs.grass_desktop_build == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        #if: steps.grass-version-check.outputs.grass_build == 'true' || steps.grass-node-version-check.outputs.grass_node_build == 'true' || steps.grass-desktop-version-check.outputs.grass_desktop_build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        #if: steps.grass-version-check.outputs.grass_build == 'true' || steps.grass-node-version-check.outputs.grass_node_build == 'true' || steps.grass-desktop-version-check.outputs.grass_desktop_build == 'true'
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     

      - name: Build and Push Grass-Desktop Image
        # Grass Desktop builds if grass_desktop_build == true (forced or version changed)
        #if: steps.grass-desktop-version-check.outputs.grass_desktop_build == 'true'
        uses: docker/build-push-action@v6
        with:
          file: "grass-desktop.dockerfile"
          push: true
          tags: ${{ env.GRASS_DESKTOP_IMAGE_NAME }}:${{ env.TAG }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

   
